name = "sookshum-labs-website-2"
type = "javascript"

[build]
command = "npm run build"

[pages]
pages_build_output_dir = "out"

[build.upload]
format = "modules"
dir = "out"  # This should match where the static files are generated
